---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: nvidia.com/sriov_rdma_vf
  name: oci-rdma-sriov
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "oci-rdma-sriov",
      "plugins": [
        {
          "type": "sriov",
          "name": "sriov-network",
          "spoofchk": "off",
          "ipam": {
            "type": "nv-ipam",
            "poolName": "default"
          }
        },
        { "type": "tuning",
          "sysctl": {
            "net.ipv4.conf.all.arp_announce": "2",
            "net.ipv4.conf.all.arp_filter": "1",
            "net.ipv4.conf.all.arp_ignore": "1",
            "net.ipv4.conf.all.rp_filter": "0",
            "net.ipv4.conf.all.accept_local": "1"
          },
          "mtu": 4220
        },
        { "type": "rdma" },
        { "type": "sbr" }
      ]
    }