apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: nvidia.com/sriov_rdma_vf
  name: sriov-net
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "sriov-rdma-net",
      "plugins": [
        {
          "name": "sriov-rdma-net",
          "type": "sriov",
          "ipam": {
            "type": "whereabouts",
            "datastore": "kubernetes",
            "kubernetes": { "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig" },
            "range": "192.168.0.0/16",
            "exclude": [],
            "log_file": "/var/log/whereabouts.log",
            "log_level": "info"
          }
        },
        {
          "name": "sriov-rdma-net",
          "type": "tuning",
          "mtu": 4220,
          "sysctl": {
            "net.ipv4.conf.all.arp_announce": "2",
            "net.ipv4.conf.all.arp_ignore": "1",
            "net.ipv4.conf.all.rp_filter": "2",
            "net.ipv4.conf.all.accept_local": "1"
          }
        },
        { "type": "rdma" }
      ]
    }