apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: bm-gpu4-8
  namespace: nvidia-network-operator
spec:
  deviceType: netdevice
  mtu: 4220
  nicSelector:
    pfNames:
    - enp12s0f0
    - enp12s0f1
    - enp22s0f0
    - enp22s0f1
    - enp72s0f0
    - enp72s0f1
    - enp76s0f0
    - enp76s0f1
    - enp138s0f0
    - enp138s0f1
    - enp148s0f0
    - enp148s0f1
    - enp195s0f0
    - enp195s0f1
    - enp209s0f0
    - enp209s0f1
    vendor: "15b3"
  nodeSelector:
    node.kubernetes.io/instance-type: "BM.GPU4.8"
  isRdma: true
  numVfs: 1
  priority: 90
  resourceName: sriov-rdma-vf

